# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SofaBotApp', '0002_exchange_orderstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='initial_btc',
            field=models.FloatField(default=0),
        ),
    ]
