# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SofaBotApp', '0003_exchange_initial_btc'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='current_btc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exchange',
            name='current_coin',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exchange',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
