# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SofaBotApp', '0004_auto_20170807_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='current_btc',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='current_coin',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='piggy',
        ),
        migrations.AddField(
            model_name='orderstate',
            name='current_btc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderstate',
            name='current_coin',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderstate',
            name='piggy',
            field=models.FloatField(default=0),
        ),
    ]
