# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SofaBotApp', '0005_auto_20170807_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstate',
            name='orderNumber',
            field=models.BigIntegerField(default=0),
        ),
    ]
